version: '3.8'

services:
  db:
    container_name: odoo_postgres_15_db
    image: postgres:15-alpine
    env_file:
      - .env_db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: on-failure
    networks:
      - mime-connect-docker-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-odoo}"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  odoo17_web:
    container_name: odoo17_web
    image: odoo:17.0
    build:
      context: .
      dockerfile: Dockerfile
    command: odoo -u all
    depends_on:
      - db
    ports:
      - "8069:8069"
    expose:
      - "8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./ai_interview_coach:/mnt/extra-addons
      - ./requirements.txt:/requirements.txt
    restart: always
    networks:
      - mime-connect-docker-net

networks:
  mime-connect-docker-net:
    external: true

volumes:
  odoo-web-data: {}
  odoo-db-data: {}
